### ISSUE TITLE
missing setuptools for pipx on Python 3.12

### ISSUE THREAD

**Issue by zachvalenta** [AnirudhG07/Typeinc#3]
`typeinc` fails if installed without also installing (or in the case of pipx, injecting) `setuptools` into your environment on Python 3.12.

```sh
# install
$ pipx install typeinc
  installed package typeinc 1.0.0, installed using Python 3.12.1
  These apps are now globally available
    - typeinc
done! ✨ 🌟 ✨

# errs out
$ typeinc
Traceback (most recent call last):
  File "/Users/zach/.local/bin/typeinc", line 7, in <module>
    from typeinc.main import main
  File "/Users/zach/Library/Application Support/pipx/venvs/typeinc/lib/python3.12/site-packages/typeinc/main.py", line 5, in <module>
    from .configurations.text_gen import text_gen
  File "/Users/zach/Library/Application Support/pipx/venvs/typeinc/lib/python3.12/site-packages/typeinc/configurations/text_gen.py", line 3, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

# solution
$ pipx inject typeinc setuptools
  injected package setuptools into venv typeinc
done! ✨ 🌟 ✨
```

**Comment by AnirudhG07** [comment]
Ill look into this.
Thanks for telling!

**Comment by AnirudhG07** [comment]
please check now. Try building from source as mentioned in readme. Please tell me if it works.

**Comment by zachvalenta** [comment]
Thanks for adding that to the docs!

I'd really rather not install packages outside of the typical pkg mgmt workflows (pip, pipx, Poetry, et al.), so I don't think a solution that goes back to `python setup.py install` would work for me. But that might just be my ignorance; I got into Python after the point at which setup.py was the prevailing way of doing things.

**Comment by AnirudhG07** [comment]
> Thanks for adding that to the docs!

Umm, i didnt add anything hehe. Also i have changed the manual installation instructions. Do check it out. I think the issues should be solved now. 
I understand u want to use with `pipx`, I will be releasing v1.0.1 soon and in that, all your issues should be solved. Thanks so much
