### ISSUE TITLE
errs out when trying to save results file

### ISSUE THREAD

**Issue by zachvalenta** [AnirudhG07/Typeinc#4]
I wasn't able to find any result file after this error (although I'm not sure where they *would* be saved; CWD? `.config/typeinc`?)

```sh
$ typeinc
Do you want to save the result? (y/n): y
Enter your name: zach
Your score is saved. To see the top 10 scores, run `typeinc -r <difficulty level>`
Thank you for playing!
An error occurred: endwin() returned ERR
Exiting typeinc...
```

**Comment by AnirudhG07** [comment]
These will be saved where the typeinc is installed, i.e. in `site-packages` of python
try `$ whereis typeinc`
then dig inside to `./typeinc/scores/scores.json`
You will find your scores there.

as far as I see the `endwin()` issue, it is related to ncurses.
I'll look into this.

**Comment by AnirudhG07** [comment]
Is there any way I can reproduce ur issue? I am not facing any similar issues at my end.

**Comment by zachvalenta** [comment]
I think this is downstream of [this issue](https://github.com/AnirudhG07/Typeinc/issues/3) i.e. unable to dig through `site-packages` until install ironed out.

**Comment by AnirudhG07** [comment]
I tried out, and in Linux I am getting this issue, however on macos the text "endwin() returned ERR
 doesn't show up.
Although this does not affect the results not being saved. They are perfectly saved as expected.

I am unable to figure out Why it is popping up, i tried different things here and there. I have currently ignored it. Will look into it.
